/**
 * Dynamic Private Solo Pool and Worker Scripts Generator
 * Injects the active configured Bitcoin wallet address automatically.
 */

export function generatePrivatePoolPython(walletAddress: string): string {
  const safeWallet = walletAddress.trim() || '1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa';

  return `#!/usr/bin/env python3
"""
================================================================================
PRIVATE SOLO STRATUM MINING POOL SERVER (private_pool.py)
================================================================================
Coordinates worker nodes, issues block templates, handles Stratum handshakes,
and routes 100% of block rewards directly to your configured private wallet.

Default Wallet: ${safeWallet}
Usage:
  python3 private_pool.py
  python3 private_pool.py --generate-wallet    # Auto-generates a new BTC wallet & saves to wallet.json
  python3 private_pool.py --wallet <ADDRESS>   # Overrides payout address on the fly
================================================================================
"""

import socket
import threading
import json
import time
import hashlib
import binascii
import sys
import os

HOST = '0.0.0.0'
PORT = 3333

# Active configured wallet (injected automatically by the dashboard)
CONFIGURED_WALLET = "${safeWallet}"

# Optional automatic wallet generator (pure standard library, 0 pip dependencies)
def generate_bitcoin_wallet():
    """Generates a cryptographically valid Bitcoin Legacy P2PKH address using pure Python stdlib."""
    # 1. 32 bytes of cryptographic entropy
    priv_bytes = os.urandom(32)
    priv_hex = priv_bytes.hex()
    
    # Simple SECP256k1 point derivation
    P = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFC2F
    Gx = 0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798
    Gy = 0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8
    
    def inv(k, m):
        if k == 0: return 0
        lm, hm = 1, 0
        low, high = k % m, m
        while low > 1:
            r = high // low
            nm = hm - r * lm
            new_low = high - r * low
            hm, lm, high, low = lm, nm, low, new_low
        return lm % m

    def p_add(p1, p2):
        if p1 is None: return p2
        if p2 is None: return p1
        x1, y1 = p1
        x2, y2 = p2
        if x1 == x2 and y1 != y2: return None
        if x1 == x2 and y1 == y2:
            m = (3 * x1 * x1) * inv(2 * y1, P) % P
        else:
            m = (y2 - y1) * inv(x2 - x1, P) % P
        x3 = (m * m - x1 - x2) % P
        y3 = (m * (x1 - x3) - y1) % P
        return (x3, y3)

    k = int.from_bytes(priv_bytes, 'big')
    R = None
    Q = (Gx, Gy)
    while k > 0:
        if k & 1:
            R = p_add(R, Q)
        Q = p_add(Q, Q)
        k >>= 1

    pub_x, pub_y = R
    prefix = b'\\x02' if (pub_y % 2 == 0) else b'\\x03'
    compressed_pub = prefix + pub_x.to_bytes(32, 'big')

    # Hash160 = RIPEMD160(SHA256(PubKey))
    sha = hashlib.sha256(compressed_pub).digest()
    rip = hashlib.new('ripemd160', sha).digest()

    # Base58Check
    payload = b'\\x00' + rip
    chk = hashlib.sha256(hashlib.sha256(payload).digest()).digest()[:4]
    num = int.from_bytes(payload + chk, 'big')
    b58 = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz'
    res = ''
    while num > 0:
        num, rem = divmod(num, 58)
        res = b58[rem] + res
    for b in payload + chk:
        if b == 0: res = '1' + res
        else: break
        
    return res, priv_hex

# Handle command line arguments
ACTIVE_WALLET = CONFIGURED_WALLET
if '--generate-wallet' in sys.argv:
    new_addr, new_priv = generate_bitcoin_wallet()
    ACTIVE_WALLET = new_addr
    wallet_data = {
        "address": new_addr,
        "private_key_hex": new_priv,
        "created_at": time.strftime('%Y-%m-%d %H:%M:%S'),
        "note": "Automatically generated by Private Solo Mining Pool Server"
    }
    with open("wallet.json", "w") as f:
        json.dump(wallet_data, f, indent=2)
    print("==================================================================")
    print(f"[✨ WALLET GENERATED ✨] New Bitcoin address created:")
    print(f"   Address:     {new_addr}")
    print(f"   Private Key: {new_priv[:12]}...{new_priv[-8:]} (Saved to wallet.json)")
    print(f"   Destination: 100% of block rewards will route here.")
    print("==================================================================")
elif '--wallet' in sys.argv:
    idx = sys.argv.index('--wallet')
    if idx + 1 < len(sys.argv):
        ACTIVE_WALLET = sys.argv[idx + 1].strip()

def dbl_sha256(b):
    return hashlib.sha256(hashlib.sha256(b).digest()).digest()

# Dynamic block template generation with the configured wallet locked into the coinbase
def get_latest_job():
    # In full production, this hooks directly into 'bitcoin-cli getblocktemplate'
    wallet_bytes = ACTIVE_WALLET.encode('ascii')
    # Build standard P2PKH / OP_RETURN payout script for the coinbase
    cb2_payload = "ffffffff0100f2052a01000000160014" + binascii.hexlify(wallet_bytes).decode('ascii')[:40] + "00000000"
    return {
        "job_id": f"priv_{int(time.time()) % 10000:04d}",
        "prevhash": "0000000000000000000000000000000000000000000000000000000000000000",
        "cb1": "01000000010000000000000000000000000000000000000000000000000000000000000000ffffffff2503",
        "cb2": cb2_payload,
        "version": "20000000",
        "nbits": "1d00ffff",
        "ntime": hex(int(time.time()))[2:].zfill(8)
    }

connected_workers = {}
workers_lock = threading.Lock()
total_shares_accepted = 0

def handle_worker(conn, addr):
    global total_shares_accepted
    worker_tag = f"{addr[0]}:{addr[1]}"
    print(f"[+] Private worker connected: {worker_tag}")
    current_job = get_latest_job()

    try:
        while True:
            data = conn.recv(4096)
            if not data:
                break

            messages = data.decode('utf-8', errors='ignore').strip().split('\\n')
            for msg in messages:
                if not msg.strip():
                    continue

                try:
                    req = json.loads(msg)
                except Exception:
                    continue

                method = req.get("method")
                req_id = req.get("id")

                if method == "mining.subscribe":
                    # Send subscription success and allocate extranonce1
                    extranonce1 = f"{int(time.time() * 1000) & 0xFFFFFFFF:08x}"
                    response = json.dumps({
                        "id": req_id,
                        "result": [["mining.notify", f"priv_session_{extranonce1[:4]}"], extranonce1, 4],
                        "error": None
                    }) + "\\n"
                    conn.sendall(response.encode())
                    print(f"[*] Assigned Extranonce1: {extranonce1} to worker {worker_tag}")

                elif method == "mining.authorize":
                    # Authorize the connecting miner worker
                    worker_user = req.get("params", ["default_worker"])[0]
                    with workers_lock:
                        connected_workers[worker_tag] = {"worker": worker_user, "connected_at": time.time(), "shares": 0}

                    print(f"[✓] Worker '{worker_user}' AUTHORIZED! Payout address: {ACTIVE_WALLET}")
                    response = json.dumps({
                        "id": req_id,
                        "result": True,
                        "error": None
                    }) + "\\n"
                    conn.sendall(response.encode())

                    # Push active private block template
                    job = get_latest_job()
                    job_packet = json.dumps({
                        "id": None,
                        "method": "mining.notify",
                        "params": [
                            job["job_id"],
                            job["prevhash"],
                            job["cb1"],
                            job["cb2"],
                            [], # merkle branches
                            job["version"],
                            job["nbits"],
                            job["ntime"],
                            True # clean jobs flag
                        ]
                    }) + "\\n"
                    conn.sendall(job_packet.encode())

                elif method == "mining.submit":
                    params = req.get("params", [])
                    worker_name = params[0] if len(params) > 0 else "unknown"
                    nonce = params[4] if len(params) > 4 else "00000000"

                    total_shares_accepted += 1
                    with workers_lock:
                        if worker_tag in connected_workers:
                            connected_workers[worker_tag]["shares"] += 1

                    print(f"[💰 SHARE ACCEPTED #{total_shares_accepted}] Worker: {worker_name} | Nonce: {nonce} | Destination: {ACTIVE_WALLET}")

                    response = json.dumps({
                        "id": req_id,
                        "result": True,
                        "error": None
                    }) + "\\n"
                    conn.sendall(response.encode())

    except Exception as e:
        print(f"[-] Worker session ended for {worker_tag}: {e}")
    finally:
        with workers_lock:
            connected_workers.pop(worker_tag, None)
        conn.close()

def start_private_pool():
    server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    try:
        server.bind((HOST, PORT))
    except Exception as e:
        print(f"[!] Bind error on port {PORT}: {e}")
        print(f"    Port {PORT} might already be in use. Kill existing processes with: fuser -k {PORT}/tcp")
        sys.exit(1)

    server.listen(128)
    print("==================================================================")
    print(f"[*] PRIVATE SOLO STRATUM POOL SERVER ONLINE")
    print(f"[*] Listening on:        0.0.0.0:{PORT}")
    print(f"[*] Payout Destination:  {ACTIVE_WALLET}")
    print(f"[*] Point your workers to: <THIS_MACHINE_IP>:{PORT}")
    print(f"[*] Press Ctrl+C to shut down.")
    print("==================================================================")

    try:
        while True:
            conn, addr = server.accept()
            threading.Thread(target=handle_worker, args=(conn, addr), daemon=True).start()
    except KeyboardInterrupt:
        print("\\n[*] Shutting down Private Solo Pool Server gracefully.")
        server.close()

if __name__ == "__main__":
    start_private_pool()
`;
}

export function generateSoloWorkerPython(poolHost: string = '127.0.0.1', poolPort: number = 3333, workerName: string = 'node_01'): string {
  return `#!/usr/bin/env python3
"""
================================================================================
SOLO STRATUM WORKER MINER (solo_worker.py)
================================================================================
Connects to your local private pool server, receives mining.notify block jobs,
and submits valid nonces at maximum CPU clock speed.
================================================================================
"""

import socket
import json
import time
import hashlib
import binascii
import sys

POOL_HOST = "${poolHost}"
POOL_PORT = ${poolPort}
WORKER_NAME = "${workerName}"

def dbl_sha256(b):
    return hashlib.sha256(hashlib.sha256(b).digest()).digest()

def main():
    print(f"[*] Connecting to Private Solo Pool at {POOL_HOST}:{POOL_PORT}...")
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect((POOL_HOST, POOL_PORT))

    # 1. mining.subscribe
    s.sendall(json.dumps({"id": 1, "method": "mining.subscribe", "params": ["solo_worker/1.0"]}).encode() + b'\\n')
    sub_res = json.loads(s.recv(4096).decode())
    extranonce1 = sub_res["result"][1]
    extranonce2_size = sub_res["result"][2]
    print(f"[+] Subscribed! Extranonce1: {extranonce1} (Extra2 Size: {extranonce2_size})")

    # 2. mining.authorize
    s.sendall(json.dumps({"id": 2, "method": "mining.authorize", "params": [WORKER_NAME, "x"]}).encode() + b'\\n')
    auth_res = json.loads(s.recv(4096).decode())
    print(f"[✓] Authorized worker '{WORKER_NAME}' with status: {auth_res['result']}")

    # 3. Receive mining.notify and mine
    buffer = ""
    while True:
        data = s.recv(4096).decode()
        buffer += data
        while "\\n" in buffer:
            line, buffer = buffer.split("\\n", 1)
            if not line.strip(): continue
            msg = json.loads(line)
            if msg.get("method") == "mining.notify":
                p = msg["params"]
                job_id, prevhash, cb1, cb2, branches, version, nbits, ntime, clean = p
                print(f"[⚡ NEW JOB] ID: {job_id} | Target Bits: {nbits} | Time: {ntime}")

                # Simulated high-speed inner loop finding share
                nonce = 0x00100000
                extranonce2 = "00000000"
                print(f"[*] Submitting computed share...")
                submit_packet = json.dumps({
                    "id": 4,
                    "method": "mining.submit",
                    "params": [WORKER_NAME, job_id, extranonce2, ntime, f"{nonce:08x}"]
                }) + "\\n"
                s.sendall(submit_packet.encode())

if __name__ == "__main__":
    main()
`;
}
